### ISSUE TITLE
filemoon embed url

### ISSUE THREAD

**Issue by Rhiannon99** [Inside4ndroid/vidsrc-api-js#1]
i deployed this respo and im getting 500: INTERNAL_SERVER_ERROR please ix it and could u please add filemoon embed url just the embed url thank you so much

**Comment by Inside4ndroid** [comment]
i have fixed the api not added filemoon yet though but F2Cloud (formerly vidsrc) works as it should.

**Comment by Inside4ndroid** [comment]
i have added filemoon extractor :)
