### ISSUE TITLE
This is very good but I think there should be different providers

### ISSUE THREAD

**Issue by robert7810** [Inside4ndroid/vidsrc-api-js#11]
Embed.su works but some movies don’t player when I put them into my payer also asiaheroku doesn’t work for me at all so could you add vidlink.pro as another provider because they have multiple sources. Or catflix.su which has a very stable source

**Comment by robert7810** [comment]
and heartive.pages.dev has a bunch of source that you can scrape from

**Comment by RISHAB-CREATOR** [comment]
> and heartive.pages.dev has a bunch of source that you can scrape from

my guys its just embed wrapper
use https://www.rgshows.me 
da best in da world

**Comment by robert7810** [comment]
Also I found this api https://moviekex.online/server

**Comment by itsallan** [comment]
> Also I found this api https://moviekex.online/server

how do you use it because it doesn't use tmdb ids
