### ISSUE TITLE
why is it blank 

### ISSUE THREAD

**Issue by itsallan** [Inside4ndroid/vidsrc-api-js#12]
![Screenshot 2024-11-19 193654](https://github.com/user-attachments/assets/be1f5650-5b2a-4cf2-abd1-7b84a08ee389)
  i don't know if am doing anything wrong because it works locally but when  i host it, i get a blank page

**Comment by Inside4ndroid** [comment]
seems to be an issue with vercel as it runs perfectly locally... i am looking into it.

**Comment by itsallan** [comment]
Okay so should we expect a solution?

**Comment by Inside4ndroid** [comment]
Well the owner of embed.su
blocked all the request from vercel

You all have to use a new host
As of now im using onrender, might be a better alternative
link : https://onrender.com/
the scrapper works fine if it hosted on this
