### ISSUE TITLE
site is blank embed.su patched

### ISSUE THREAD

**Issue by hexatv** [Inside4ndroid/vidsrc-api-js#13]

**Comment by Inside4ndroid** [comment]
seems to be an issue with vercel as it runs perfectly locally... i am looking into it.

**Comment by hexatv** [comment]
yes :(

**Comment by Inside4ndroid** [comment]
Well the owner of embed.su
blocked all the request from vercel

You all have to use a new host
As of now im using onrender, might be a better alternative
link : https://onrender.com/
the scrapper works fine if it hosted on this

**Comment by Inside4ndroid** [comment]
Well the owner of embed.su
blocked all the request from vercel

You all have to use a new host
As of now im using onrender, might be a better alternative
link : https://onrender.com/
the scrapper works fine if it hosted on this
