### ISSUE TITLE
site blank

### ISSUE THREAD

**Issue by heyitsleo** [Inside4ndroid/vidsrc-api-js#14]
ik this has been mentioned several times, but from what ive seen it worked with my fixed code but deploying it yet again showed me a blank output; regardless it worked on localhost aswell; and koyeb but nothings better than the vercel one. are we able to expect a fix?

**Comment by heyitsleo** [comment]
like using vidsrc.cc, or something different?

**Comment by Inside4ndroid** [comment]
Well the owner of embed.su
blocked all the request from vercel

You all have to use a new host
As of now im using onrender, might be a better alternative
link : https://onrender.com/
the scrapper works fine if it hosted on this
