### ISSUE TITLE
Found a fix 👍 

### ISSUE THREAD

**Issue by RISHAB-CREATOR** [Inside4ndroid/vidsrc-api-js#15]
Well the owner of embed.su
just blocked all the request from vercel
You all have to use a new host
As of now i m using onrender, might be a better alternative
link : https://onrender.com
the scrapper works fine if it hosted on this

**Comment by R-BTW** [comment]
Hey thanks man it worked!

**Comment by itsallan** [comment]
you are a hero

**Comment by Inside4ndroid** [comment]
@RISHAB-CREATOR Thanks i have updated the README to reflect this and i am working on a few other providers so will have an update for this repo in due course. :)
