### ISSUE TITLE
500: INTERNAL_SERVER_ERROR

### ISSUE THREAD

**Issue by Microgramx** [Inside4ndroid/vidsrc-api-js#2]
im getting 500: INTERNAL_SERVER_ERROR what i need to do ?

**Comment by Inside4ndroid** [comment]
seems to be an issue with vercel???

running locally it works just fine..

i shall look into it and see if i can produce a fix.

**Comment by Inside4ndroid** [comment]
all working now. :)

**Comment by Microgramx** [comment]
Hello, good morning, thanks so much for your reply, I'll try now
