### ISSUE TITLE
Vidsrc.to is back

### ISSUE THREAD

**Issue by M4X1MUS07** [Inside4ndroid/vidsrc-api-js#7]
Would it be possible for you to revert this API to vidsrc.to again? They are now back with their new domain https://vidsrc2.to/

vidsrc.cc uses rabbitstream's url which are kind of getting slower recently, implementing vidsrc.to again would be super nice.
anyways thanks for this super cool project though, appreciate it!

**Comment by hurgir** [comment]
probably a change in the encryption method https://github.com/recloudstream/cloudstream/pull/1287

**Comment by Inside4ndroid** [comment]
all fixed although it now uses a different domain :)

**Comment by gilbertlucas46** [comment]
its actually https://embed.su right?

**Comment by Inside4ndroid** [comment]
> its actually https://embed.su right?

yeah thats right VidsrcPro alternative

**Comment by Jahvon-DS** [comment]
is anyone getting a 403 Forbbidden errror for `dataDirect`?
